version: "3.9"

x-traefik-label: &traefik-label
  traefik.enable: true
  traefik.http.routers.puter.service: puter
  traefik.http.services.puter.loadbalancer.server.port: 4100

services:
  puter:
    container_name: puter
    image: heyputer/puter:latest # ghcr.io/heyputer/puter:latest
    pull_policy: always
    ports:
      - "4100:4100"
    labels:
      <<: *traefik-label
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - /volume5/storage/docker-data/puter/conf/:/etc/puter/
      - /volume5/storage/docker-data/puter/data/:/var/puter/
    restart: always