version: "3.9"

x-traefik-label: &traefik-label
  traefik.enable: true
  traefik.http.routers.homepage.service: homepage
  traefik.http.services.homepage.loadbalancer.server.port: 3000

services:

  homepage:
    image: "registry-proxy.czy21.com/gethomepage/homepage:v0.9.5" # ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    hostname: homepage
    labels:
      <<: *traefik-label
    privileged: true
    user: root
    volumes:
      - /volume5/storage/docker-data/homepage/conf/:/app/config/
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Shanghai
    restart: always