version: "3.9"

x-traefik-label: &traefik-label
  traefik.enable: true
  traefik.http.routers.archery.service: archery
  traefik.http.services.archery.loadbalancer.server.port: 9123

services:

  archery:
    image: hhyo/archery:v1.9.1
    container_name: archery
    labels:
      <<: *traefik-label
    privileged: true
    expose:
      - "9123"
    user: root
    volumes:
      - /volume5/storage/docker-data/archery/data/:/data/
    environment:
      NGINX_PORT: "9123"
      DEBUG: false
      DATABASE_URL: mysql://<username>:<secret_value>@<db_host>:3306/archery
      CACHE_URL: redis://192.168.20.2:6379/0?PASSWORD=<secret_value>
      CSRF_TRUSTED_ORIGINS: http://127.0.0.1:9123
      ENABLE_LDAP: false
    restart: always