version: "3.9"

x-traefik-label: &traefik-label
  traefik.enable: true
  traefik.http.routers.netbox.service: netbox
  traefik.http.services.netbox.loadbalancer.server.port: 8000

services:

  netbox:
    image: linuxserver/netbox:3.2.6
    container_name: netbox
    labels:
      <<: *traefik-label
    expose:
      - "8000"
    volumes:
      - /volume5/storage/docker-data/netbox/conf/:/config
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Shanghai
      SUPERUSER_EMAIL: 805899926@qq.com
      SUPERUSER_PASSWORD: '<secret_value>'
      ALLOWED_HOST: '*'
      DB_NAME: netbox
      DB_USER: 'postgres'
      DB_PASSWORD: '<secret_value>'
      DB_HOST: '<db_host>'
      DB_PORT: '5432'
      REDIS_HOST: '192.168.20.2'
      REDIS_PORT: '6379'
      REDIS_PASSWORD: '<secret_value>'
      REDIS_DB_TASK: 0
      REDIS_DB_CACHE: 0
    restart: always