version: "3"

x-traefik-label: &traefik-label
  traefik.enable: true
  traefik.http.routers.vaultwarden.service: vaultwarden
  traefik.http.services.vaultwarden.loadbalancer.server.port: 80

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    labels:
      <<: *traefik-label
    volumes:
      - /volume5/storage/docker-data/vaultwarden/data/:/data
    environment:
      WEBSOCKET_ENABLED: true
      SIGNUPS_ALLOWED: false
      DOMAIN: "https://vaultwarden.czy21.com"
      ADMIN_TOKEN: "<secret_value>"
      SMTP_HOST: "smtp.qq.com"
      SMTP_FROM: "805899926@qq.com"
      SMTP_PORT: "587"
      SMTP_SSL: "true"
      SMTP_USERNAME: "805899926@qq.com"
      SMTP_PASSWORD: "<secret_value>"
    restart: always