version: "3.9"

x-traefik-label: &traefik-label
  traefik.enable: true
  traefik.http.routers.metabase.service: metabase
  traefik.http.services.metabase.loadbalancer.server.port: 3000

services:

  metabase:
    image: metabase/metabase:v0.52.1.3
    container_name: metabase
    privileged: true
    user: root
    labels:
      <<: *traefik-label
    environment:
      MB_DB_TYPE: mysql
      MB_DB_DBNAME: metabase
      MB_DB_HOST: <db_host>
      MB_DB_PORT: 3306
      MB_DB_USER: <username>
      MB_DB_PASS: <secret_value>
    restart: always