version: "3.9"

x-superset-image: &superset-image apache/superset:4.0.1
x-superset-volumes: &superset-volumes
  - /volume5/storage/docker-data/superset/conf/docker/:/app/docker/
  - /volume5/storage/docker-data/superset/data/superset/:/app/superset_home

x-traefik-label: &traefik-label
  traefik.enable: true
  traefik.http.routers.superset.service: superset
  traefik.http.services.superset.loadbalancer.server.port: 8088

x-superset-env: &superset-env
  DATABASE_DB: superset
  DATABASE_HOST: "<db_host>"
  DATABASE_PORT: "3306"
  DATABASE_USER: "<username>"
  DATABASE_PASSWORD: "<secret_value>"
  EXAMPLES_DB: superset
  EXAMPLES_HOST: "<db_host>"
  EXAMPLES_PORT: "3306"
  EXAMPLES_USER: "<username>"
  EXAMPLES_PASSWORD: "<secret_value>"
  DATABASE_DIALECT: mysql
  MYSQL_DB: superset
  MYSQL_USER: "<username>"
  MYSQL_PASSWORD: "<secret_value>"
  PYTHONPATH: /app/pythonpath:/app/docker/pythonpath
  REDIS_HOST: "192.168.20.2"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "<secret_value>"
  FLASK_ENV: true
  SUPERSET_ENV: production
  SUPERSET_SECRET_KEY: production
  SUPERSET_PORT: 8088
  SUPERSET_LOAD_EXAMPLES: "yes"
  CYPRESS_CONFIG: "false"

services:

  # superset-init:
  #   image: *superset-image
  #   container_name: "superset-init"
  #   command: ["/app/docker/docker-init.sh"]
  #   user: "root"
  #   volumes: *superset-volumes
  #   environment: *superset-env

  superset:
    image: *superset-image
    container_name: superset-app
    command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
    user: "root"
    restart: always
    labels:
      <<: *traefik-label
    volumes: *superset-volumes
    environment: *superset-env

  superset-worker:
    image: *superset-image
    container_name: "superset-worker"
    command: ["/app/docker/docker-bootstrap.sh", "worker"]
    restart: always
    user: "root"
    volumes: *superset-volumes
    environment: *superset-env

  superset-worker-beat:
    image: *superset-image
    container_name: "superset-worker-beat"
    command: ["/app/docker/docker-bootstrap.sh", "beat"]
    restart: always
    user: "root"
    volumes: *superset-volumes
    environment: *superset-env