version: "3.9"

services:

  filebeat:
    image: elastic/filebeat:7.17.9
    container_name: filebeat
    privileged: true
    user: root
    volumes:
      - /volume5/storage/docker-data/filebeat/conf/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /volume5/docker-root/containers/:/var/lib/docker/containers:ro
    environment:
      ELASTICSEARCH_HOSTS: "es.czy21.com:80"
      ELASTICSEARCH_USERNAME: "<username>"
      ELASTICSEARCH_PASSWORD: "<secret_value>"
    restart: always