version: "3.9"

x-traefik-label: &traefik-label
  traefik.enable: true
  traefik.http.routers.go-backup.service: go-backup
  traefik.http.services.go-backup.loadbalancer.server.port: 2703

services:

  go-backup:
    image: huacnlee/gobackup:v2.15.3
    container_name: go-backup
    labels:
      <<: *traefik-label
    privileged: true
    expose:
      - "2703"
    user: root
    volumes:
      - /volume5/storage/docker-data/go-backup/conf/config.yml:/etc/gobackup/gobackup.yml
      - /volume5/storage/docker-data/go-backup/backup/:/root/backup/
    restart: always

