version: "3.9"

services:
  logstash:
    image: logstash:8.11.3
    container_name: logstash
    hostname: logstash
    privileged: true
    user: root
    ports:
      - 4560:4560 # spring
    volumes:
      - /volume5/storage/docker-data/logstash/data/:/usr/share/logstash/data/
      - /volume5/storage/docker-data/logstash/conf/logstash.yml:/usr/share/logstash/config/logstash.yml
      - /volume5/storage/docker-data/logstash/conf/pipeline/:/usr/share/logstash/pipeline/
      - /volume5/storage/docker-data/app/log/:/app/log/
    restart: no # 避免连接不上es,cpu负载高以及产生大量jruby文件