version: "3.9"

x-traefik-label-server: &traefik-label-server
  traefik.enable: true
  traefik.http.routers.immich-server.service: immich-server
  traefik.http.services.immich-server.loadbalancer.server.port: 3001

x-immich-env: &immich-env
  DB_URL: postgresql://postgres:<secret_value>@<db_host>:5435/immich
  REDIS_HOSTNAME: '192.168.20.2'
  REDIS_PASSWORD: '<secret_value>'

services:
  immich-server:
    image: immich-app/immich-server:v1.116.2 # ghcr.io/immich-app/immich-machine-learning:v1.116.2
    container_name: immich-server
    labels:
      <<: *traefik-label-server
    volumes:
      - /volume5/storage/docker-data/immich/data/photo/:/usr/src/app/upload/
    environment:
      <<: *immich-env
    restart: always

  immich-machine-learning:
    image: immich-app/immich-machine-learning:v1.116.2 # ghcr.io/immich-app/immich-machine-learning:v1.116.2
    container_name: immich-machine-learning
    volumes:
      - /volume5/storage/docker-data/immich/data/cache/:/cache/
    environment:
      <<: *immich-env
    restart: always