http:
  routers:
    traefik:
      rule: Host(`traefik-.czy21-internal.com`)
      service: traefik@docker
    cadvisor:
      rule: Host(`cadvisor-.czy21-internal.com`)
      service: cadvisor@docker
  middlewares:
    basic-auth:
      basicAuth:
        usersFile: "/etc/traefik/conf.d/basic-auth.txt"