version: "3.9"

x-traefik-label: &traefik-label
  traefik.enable: true
  traefik.http.routers.gitea.service: gitea
  traefik.http.services.gitea.loadbalancer.server.port: 3000

services:

  gitea:
    image: gitea/gitea:1.24.2
    container_name: gitea
    labels:
      <<: *traefik-label
    privileged: true
    user: root
    expose:
      - "3000"
      - "22"
    ports:
      - "2226:22"
    volumes:
      - /volume5/storage/docker-data/gitea/data/:/data/
    environment:
      TZ: Asia/Shanghai
      GITEA__server__DOMAIN: "gitea.czy21.com"
      GITEA__server__SSH_DOMAIN: "gitea.czy21.com:2226"
      GITEA__server__ROOT_URL: "https://gitea.czy21.com:8443/"
      GITEA__server__HTTP_PORT: "3000"
      GITEA__server__LANDING_PAGE: explore
      GITEA__server__LFS_START_SERVER: true
      GITEA__server__LFS_ALLOW_PURE_SSH: true
      GITEA__security__INSTALL_LOCK: true
      GITEA__database__DB_TYPE: mysql
      GITEA__database__NAME: gitea
      GITEA__database__HOST: "<db_host>:3306"
      GITEA__database__USER: "<username>"
      GITEA__database__PASSWD: "<secret_value>"
      GITEA__packages__ENABLED: "true"
      GITEA__repository__USE_COMPAT_SSH_URI: "true"
      GITEA__ssh.minimum_key_sizes__RSA: 2048
      GITEA__attachment__MAX_SIZE: 1024
      GITEA__attachment__MAX_FILES: 20
      GITEA__webhook__ALLOWED_HOST_LIST: "*"
    restart: always