version: "3.9"

services:

  fluent:
    image: "registry.czy21.com/library/fluent"
    pull_policy: always
    container_name: fluent
    privileged: true
    user: root
    ports:
      - "24224:24224" # input
      - "24224:24224/udp"
      - "24231:24231"
    expose:
      - "24231" # metrics
    volumes:
      - /volume5/storage/docker-data/fluent/conf/:/fluentd/etc/
      - /volume5/storage/docker-data/fluent/log/:/fluentd/log/
    restart: always