bookiePort=3181
zkServers=<ip>:2181,<ip>:2182,<ip>:2183/pulsar/cluster1
zkTimeout=30000

useHostNameAsBookieID=true
journalDirectories=data/bookie/journal
ledgerDirectories=data/bookie/ledgers
autoRecoveryDaemonEnabled=false