
x-authentik-common: &authentik-common
  image: authentik/server:2026.5.4
  privileged: true
  user: root
  environment:
    AUTHENTIK_POSTGRESQL__NAME: authentik
    AUTHENTIK_POSTGRESQL__HOST: db.czy21.com
    AUTHENTIK_POSTGRESQL__PORT: 5432
    AUTHENTIK_POSTGRESQL__USER: postgres
    AUTHENTIK_POSTGRESQL__PASSWORD: Czy.190815
    AUTHENTIK_SECRET_KEY: VpI1toLhZrpqR8zzVddS7jZ3rnt90YmoP8DAIMtZr5tJ6Bx2Z12Zvh2JS8B5ig8eJk7ghPGQHno3sKiCroot
  restart: always

x-traefik-label: &traefik-label
  traefik.enable: true
  traefik.http.routers.authentik.service: authentik
  traefik.http.services.authentik.loadbalancer.server.port: 9000

services:
  authentik-server:
    <<: *authentik-common
    container_name: authentik-server
    labels:
      <<: *traefik-label
    ports:
      - "9000:9000"
    volumes:
      - /volume1/storage/docker-data/authentik/conf/templates:/templates
      - /volume1/storage/docker-data/authentik/data/:/data
    command: server

  authentik-worker:
    <<: *authentik-common
    container_name: authentik-worker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /volume1/storage/docker-data/authentik/conf/templates:/templates
      - /volume1/storage/docker-data/authentik/data/:/data
    command: worker