version: "3.9"

services:
  ubuntu-openwrt:
    image: docker.io/czy21/ubuntu-openwrt
    pull_policy: always
    container_name: ubuntu-openwrt
    hostname: ubuntu-openwrt
    user: opsor
    tty: true
    volumes:
      - /volume5/storage/docker-data/ubuntu-openwrt/data/:/data/
    restart: always