version: "3.9"

x-traefik-label: &traefik-label
  traefik.enable: true
  traefik.http.routers.drawio.service: drawio
  traefik.http.services.drawio.loadbalancer.server.port: 8080

services:
  drawio:
    image: jgraph/drawio:24.2.5
    pull_policy: always
    container_name: drawio
    labels:
      <<: *traefik-label
    privileged: true
    user: root
    restart: always