version: "3.9"

x-traefik-label: &traefik-label
  traefik.enable: true
  traefik.http.routers.open-webui.service: open-webui
  traefik.http.services.open-webui.loadbalancer.server.port: 8080

services:

  open-webui:
    image: "registry-proxy.czy21.com/open-webui/open-webui:main" # ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    hostname: open-webui
    labels:
      <<: *traefik-label
    privileged: true
    user: root
    volumes:
      - /volume5/storage/docker-data/open-webui/data/:/app/backend/data/
    environment:
      OLLAMA_BASE_URL: "http://192.168.20.16:11434"
    restart: always