share_path: 192.168.20.18/kube-

csi-driver-smb:
  image:
    baseRepo: 'registry-proxy.czy21.com' # registry.k8s.io
    smb:
      repository: /sig-storage/smbplugin
    csiProvisioner:
      repository: /sig-storage/csi-provisioner
    livenessProbe:
      repository: /sig-storage/livenessprobe
    nodeDriverRegistrar:
      repository: /sig-storage/csi-node-driver-registrar