nfs-subdir-external-provisioner:
  replicaCount: 1
  image:
    repository: registry-proxy.czy21.com/sig-storage/nfs-subdir-external-provisioner
  storageClass:
    name: nfs
    defaultClass: true
  nfs:
    server: 192.168.20.18
    path: /export/kube-