argo-workflows:
  fullnameOverride: argo-workflows
  crds:
    upgradeJob:
      image:
        repository: "registry.k8s.io/kubectl"
  controller:
    image:
      registry: "quay.io"
    workflowNamespaces: []
  server:
    image:
      registry: "quay.io"
  executor:
    image:
      registry: "quay.io"
  artifactRepository:
    s3: 
      endpoint: "minio.czy21.com"
      bucket: argo
      accessKeySecret:
        name: argo-artifact-credentials
        key: accessKey
      secretKeySecret:
        name: argo-artifact-credentials
        key: secretKey