version: "3.9"

x-traefik-label: &traefik-label
  traefik.enable: true
  traefik.http.routers.hop.service: hop
  traefik.http.services.hop.loadbalancer.server.port: 8080

services:

  hop:
    image: apache/hop-web:2.11.0
    container_name: hop
    labels:
      <<: *traefik-label
    privileged: true
    user: root
    volumes:
      - '/volume5/storage/docker-data/hop/conf/:/config/'
      - '/volume5/storage/docker-data/hop/data/:/data/'
    environment:
      HOP_PROJECT_FOLDER: /data
      HOP_PROJECT_NAME: default
      HOP_ENVIRONMENT_NAME: default
      HOP_ENVIRONMENT_CONFIG_FILE_NAME_PATHS: /config/default.json
    restart: always