version: "3.9"

x-traefik-label: &traefik-label
  traefik.enable: true
  traefik.http.routers.bitbucket.service: bitbucket
  traefik.http.services.bitbucket.loadbalancer.server.port: 7990

services:

  bitbucket:
    image: atlassian/bitbucket:8.15.0-ubuntu-jdk11
    container_name: bitbucket
    labels:
      <<: *traefik-label
    privileged: true
    user: root
    volumes:
      - /volume5/storage/docker-data/bitbucket/data/:/var/atlassian/application-data/bitbucket/
    environment:
      JDBC_DRIVER: "org.postgresql.Driver"
      JDBC_USER: "postgres"
      JDBC_PASSWORD: "<secret_value>"
      JDBC_URL: "jdbc:postgresql://<db_host>:5432/bitbucket"
    restart: always